services:
  automation-api:
    build: .
    container_name: visions-15-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./files:/label-studio/files
    depends_on:
      - label-studio

  label-studio:
    image: heartexlabs/label-studio:1.23.0
    container_name: label-studio
    ports:
      - "8080:8080"
    environment:
      LABEL_STUDIO_HOST: "http://localhost:8080"
      CSRF_TRUSTED_ORIGINS: "http://localhost:8080"
      LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: "true"
      LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT: "/label-studio/files"
    volumes:
      - ./label-studio-data:/label-studio/data
      - ./files:/label-studio/files
